### PR TITLE
PROD-2202 - Load data from api for learn/landing

### PR DESCRIPTION
**Pull request by vas3a**
https://topcoder.atlassian.net/browse/PROD-2202

Load data from api for landing of learning page

### CODE REVIEW

**Review by testflyjets — APPROVED** [review]

**Comment by testflyjets** [comment]
Awesome work!

**Review by brooketopcoder — CHANGES_REQUESTED** [review]
This all looks really good!

Per conversation, let's revise the folder structure to match our goals. https://topcoder.atlassian.net/wiki/spaces/PROD/pages/2811527191/Platform+UI+Folder+Structure

I will upload a guide.

**Comment by brooketopcoder** [comment]
[learn-folder-structure.txt](https://github.com/topcoder-platform/mfe-customer-work/files/8930904/learn-folder-structure.txt)

**Review by brooketopcoder — APPROVED** [review]
per discussion, we are going to handle the refactor of the folder structure in a separate effort/branch.

approving this as-is

**Pull request merged**
